## Matrix vs NDarray

In [2]:
import numpy as np

In [3]:
a = np.matrix("1 2;3 4")

In [5]:
b = np.array([[1, 2],[3, 4]])

In [6]:
a

matrix([[1, 2],
        [3, 4]])

In [7]:
b

array([[1, 2],
       [3, 4]])

In [8]:
a * a

matrix([[ 7, 10],
        [15, 22]])

In [9]:
b * b

array([[ 1,  4],
       [ 9, 16]])

In [10]:
b @ b

array([[ 7, 10],
       [15, 22]])

### 1D Filtering

In [13]:
c = np.array([1, 2, 3, 4, 5])

In [14]:
c

array([1, 2, 3, 4, 5])

In [15]:
c % 2 == 0

array([False,  True, False,  True, False])

In [16]:
c[c%2 == 0]

array([2, 4])

### 2D Filtering

In [52]:
a = np.arange(1,9).reshape(4,2,order='F')

In [53]:
a

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

Bitwise Logical Operator

* `&` : Bitwise and
* `|` : Bitwise or
* `^` : Bitwise xor

In [100]:
a[(a[:,0]>=2) & (a[:,0]<=3), :]

array([[2, 6],
       [3, 7]])

## Higher Order Function

In [104]:
def add_const(a):
    
    def f(x):
        return x + a
    
    return f

In [105]:
t = add_const(2)

In [106]:
t(3)

5

In [107]:
def diff(f, x):
    h = 1e-6
    return (f(x+h)-f(x)) / h

In [108]:
diff(np.sin, np.pi)

-1.0000000001396114

In [110]:
def deriv(f):
    h = 1e-6
    
    def df(x):
        return (f(x+h)-f(x)) / h
    
    return df

In [112]:
dsin = deriv(np.sin)

In [113]:
dsin(np.pi)

-1.0000000001396114

In [114]:
?np.vectorize

In [115]:
diff_vec = np.vectorize(diff)

In [116]:
dsin_vec = np.vectorize(dsin)

In [118]:
def f(x):
    if x < 0:
        return -1
    else:
        return 1

In [119]:
f(1)

1

In [120]:
f([1,2,3])

TypeError: '<' not supported between instances of 'list' and 'int'

In [121]:
f_vec = np.vectorize(f)

In [122]:
f_vec([1,2,3])

array([1, 1, 1])